language: node_js
node_js:
  - "node"
dist: trusty
sudo: required

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - npm run test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  #- ng build --prod --base-href https://bastianschott.github.io/ezMail/
	
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ezMail
  on:
    branch: master