language: node_js
node_js:
  - '10.15.1'
dist: trusty
sudo: required

addons:
  apt:
    #update: true
    chrome: stable
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  #- ng lint
  #- npm run test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - ng build --prod --base-href './'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ezMail
  on:
    branch: master
