language: node_js
node_js:
  - "node"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $pages
  keep_history: true
  on:
    branch: gh-pages